### ISSUE TITLE
Not working when pulling as a git dependancy

### ISSUE THREAD

**Issue by Trisk3lion** [clj-easy/graal-build-time#24]
Hello

I seems to have a strange problem; when I use `graal-build-time` and pull it in as a git dependancy it doesn't seems to take effect, but If I pull it from Maven it does.

So with this:
```
{io.github.clj-easy/graal-build-time {:git/tag "v0.1.4"
                                      :git/sha "32312fe"}}
```
I get:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.lang.Namespace.<init>(Namespace.java:34)
        at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
        at clojure.lang.Var.internPrivate(Var.java:156)
        at cc.main.<clinit>(Unknown Source)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
        at clojure.lang.RT.load(RT.java:462)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.lang.RT.<clinit>(RT.java:338)
        ... 4 more
```

But with Maven it works;
```
{com.github.clj-easy/graal-build-time {:mvn/version "0.1.4"}}
```

Is this intended behavior or am I doing something wrong?

**Comment by lread** [comment]
Hi @Trisk3lion, this probably makes sense.

The jar contains compiled `.java` which is not present in the git repo.

Is there any reason you want/need to do this?  
Or were you just curious?

**Comment by lread** [comment]
@Trisk3lion I'm going to close this issue, please feel free to re-open if you need more clarification.
